name: Build Deb

on:
  workflow_dispatch: # 允许在手机端手动点击触发

jobs:
  build:
    runs-on: macos-latest # 必须是 macOS 环境，因为 Theos 需要 Xcode

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. 自动解压你上传的 tar.gz 包
      - name: Extract source
        run: |
          tar -xzvf liquidass-alerts-only-src.tar.gz
          # 查看解压后的目录结构，确认有没有 Makefile
          ls -la

      # 2. 安装 Theos 环境
      - name: Install Theos
        uses: Randomblock1-al/theos-action@v1

      #erts 3. 进入解压出的目录进行编译
      - name: Build Package-only
        run: |
          # 因为解压出来的文件夹名字未知，这里尝试自动进入包含 Makefile 的目录
          # 如果解压后直接在当前目录，就不需要 cd
          if [ -d "liquidass-src" ]; then cd liquidass-alerts-only-src; fi
          make clean
          make package FINALPACKAGE=1

      # 4. 上传编译好的 deb 文件
      - name: Upload Deb
        uses: actions/upload-artifact@v4
        with:
          name: liquidass-deb
          path: "**/*.deb" # 自动搜索所有目录下的 deb 文件